plugins:
  - jekyll-default-layout

title: Clinical Neurosciences
description: YOUR DESCRIPTION
remote_theme: pmarsceill/just-the-docs

url: https://KNW-ANW.github.io/KNW-ANW

# Set a path/url to a logo that will be displayed instead of the title
logo: "/images/brain.png"
